Vantage/Controllers/HouseManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vantage.Data;
using Vantage.Models;

namespace Vantage.Controllers
{
    public class HouseManagementController : Controller
    {
        // GET: HouseManagement or HouseManagement/Index
        public ActionResult Index()
        {
            // TODO: Make a home page for House Management
            //return View("HouseManagementHome");
            return new HttpStatusCodeResult(400, "Page not created yet");
        }

        // GET: HouseManagement/DutySheet
        public ActionResult DutySheet()
        {
            DutySheetViewModel viewModel = new DutySheetViewModel()
            {
                Duties = HouseManagementData.GetDuties(),
                WeekDay = ConvertDayOfWeekToInt(DateTime.Now.DayOfWeek)
            };

            return View("DutySheet", viewModel);
        }

        public ActionResult HousePoints()
        {
            HousePointsViewModel viewModel = new HousePointsViewModel();
            return View("HousePoints", viewModel);
        }

        public ActionResult Fines()
        {
            FinesViewModel viewModel = new FinesViewModel();
            return View("Fines", viewModel);
        }

        // Converts the week day to a number used by the Duty Models
        private int ConvertDayOfWeekToInt(DayOfWeek day)
        {
            switch (day)
            {
                case DayOfWeek.Sunday: return 0;
                case DayOfWeek.Monday: return 1;
                case DayOfWeek.Tuesday: return 2;
                case DayOfWeek.Wednesday: return 3;
                case DayOfWeek.Thursday: return 4;
                case DayOfWeek.Friday: return 5;
                case DayOfWeek.Saturday: return 6;
                default: throw new ArgumentException("Day of week invalid");
            }
        }
    }
}

Vantage/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vantage.Data;
using Vantage.Models;

namespace Vantage.Controllers
{
    public class InfoController : Controller
    {

        // GET: Info or Info/Index
        public ActionResult Index()
        {
            // TODO: Make a home page for Information
            //return View("InformationHome");
            return new HttpStatusCodeResult(400, "Page not created yet");
        }

        // GET: Information/Directory
        public ActionResult Directory()
        {
            DirectoryViewModel viewModel = new DirectoryViewModel()
            {
                TestVar = "Hello, world!",
                Members = InformationData.GetMembers()
            };
            return View("Directory", viewModel);
        }

        public ActionResult MessageBoard()
        {
            MessageBoardModel model = new MessageBoardModel();
            return View("MessageBoard", model);
        }
    }
}

Vantage/Views/Shared/ModalPartial.cshtml
<!-- Bootstrap Modal -->
<div class="modal fade" id="commonModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="commonModalTitle"></h4>
            </div>
            <div class="modal-body">
                <p id="commonModalBody"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Vantage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <script src="@Url.Content("~/Scripts/common.js")"></script>

    @RenderSection("PageScripts", false /*required*/)
    @RenderSection("PageStyles", false /*required*/)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Vantage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Directory", "Directory", "Info")</li>
                    <li>@Html.ActionLink("Duties", "DutySheet", "HouseManagement")</li>
                    <li>@Html.ActionLink("Fines", "Fines", "HouseManagement")</li>
                    <li>@Html.ActionLink("House Points", "HousePoints", "HouseManagement")</li>
                    <li>@Html.ActionLink("Message Board", "MessageBoard", "Info")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PKP Vantage
            <span style="float:right">Developed by Derek Coley, Jake Magill</span> 
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>